import useProfile from "@/hooks/useProfile";
import useStation from "@/hooks/useStation";
import { Avatar, Box, Text } from "@mantine/core";
import Head from "next/head";

const MyDesk = () => {
    const { profile } = useProfile()
    const { station } = useStation(1)

    console.log(profile)
    console.log("stn", station)

    return ( 
        <>
            <Head>
                <title>IMA | My Desk</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Box>
                <Text>This is my desk</Text>
                {profile ? 
                    <>
                        <Avatar>{profile.firstName}</Avatar>
                    </> : undefined}
            </Box>
        </>
     );
}
 
export default MyDesk;