import DropZone from "@/components/Office/DropZone";
import InactiveUsers from "@/components/Office/InactiveUsers";
import Stations from "@/components/Office/Stations";
import useStations from "@/hooks/useStations";
import { Box, useMantineTheme, Text } from "@mantine/core";
import { useMediaQuery } from "@mantine/hooks";
import Head from "next/head";

const Office = () => {
    const { stations, loading } = useStations()
    const { breakpoints } = useMantineTheme()
    const isLarge = useMediaQuery(`(min-width: ${breakpoints.lg})`)

    return ( 
        <>
            <Head>
                <title>IMA | Office</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            
            {isLarge ? <Box 
                sx={({ colors, colorScheme }) => ({ 
                    position: "relative",
                    width: "100%",
                    maxWidth: 1200,
                    margin: "0 auto",
                    height: "100%",
                    minHeight: 800,
                    background: colorScheme === "dark" ? colors.dark[5] : colors.gray[2],
                    userSelect: "none",
                })}
            >
                <Stations stations={stations} />
                <InactiveUsers />
                <DropZone />            
            </Box>
            :
            <Box>
                <Text>Must be viewed on large screen</Text>
            </Box>
            }
        </>
     );
}
 
export default Office;