import DropZone from "@/components/Office/DropZone";
import InactiveComputors from "@/components/Office/InactiveComputors";
import InactiveUsers from "@/components/Office/InactiveUsers";
import Stations from "@/components/Office/Stations";
import ToolBar from "@/components/Office/ToolBar";
import { DraggingProvider } from "@/context/DraggingContext";
import { ShowTooltipsProvider } from "@/context/ShowTooltipsContext";
import { Box, useMantineTheme, Text } from "@mantine/core";
import { useMediaQuery } from "@mantine/hooks";
import Head from "next/head";

const Office = () => {
    const { breakpoints } = useMantineTheme()
    const isLarge = useMediaQuery(`(min-width: ${breakpoints.lg})`)

    return ( 
        <>
            <Head>
                <title>IMA | Office</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            
            <DraggingProvider>
                <ShowTooltipsProvider>
                    {isLarge ? <Box 
                        sx={({ colors, colorScheme, shadows }) => ({ 
                            position: "relative",
                            width: "100%",
                            maxWidth: 1200,
                            margin: "0 auto",
                            height: "100%",
                            minHeight: 800,
                            background: colorScheme === "dark" ? colors.dark[5] : colors.gray[2],
                            userSelect: "none",
                            boxShadow: colorScheme === "dark" ? "inset 0 0 2px 1px rgba(255,255,255,.1)": `inset ${shadows.xl}`, 
                            borderRadius: 4,
                        })}
                    >
                        <ToolBar />
                        <Stations />
                        <InactiveUsers />
                        <DropZone />     
                        <InactiveComputors />       
                    </Box>
                    :
                    <Box>
                        <Text>Must be viewed on large screen</Text>
                    </Box>
                    }
                </ShowTooltipsProvider>
            </DraggingProvider>
        </>
     );
}
 
export default Office;