import { Box } from "@mantine/core";
import Head from "next/head";

const Admin = () => {
    return ( 
        <>
            <Head>
                <title>IMA | Admin</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Box>
                Admin page
            </Box>
        </>
     );
}
 
export default Admin;